Symboltable wind mill signals
GCWizard/GCWizard pull request #2025
Opened 2024-11-27 11:36 UTC by olliklee

Added 2 new Symbol tables.
Corrected a wrong entry on wingdings.
Waiting for a license update for wind_mill_signals_V2

2024-11-27 16:18 UTC, Mike-3 commented
change color deep to 1 bit.

2025-01-23 13:52 UTC, S-Man42 commented
what about this one? Ready or still WIP?

2025-01-23 16:31 UTC, olliklee commented
Ready and done, but waiting for the second table's license.

2025-02-17 18:47 UTC, t-m-z requested changes
please change "https://www.braunsmuehle.de" esp. the website with the code to a webarchive link to save the webpage

2025-02-17 19:48 UTC, Mike-3 commented
change target branch

2025-02-17 23:19 UTC, olliklee reviewed
Changed base branch

2025-02-18 14:38 UTC, Mike-3 commented
solve conflics

2025-02-19 11:48 UTC, closed without merging