Added 16 Trithemius symbol tables
GCWizard/GCWizard pull request #2026
Opened 2024-11-27 13:49 UTC by olliklee

Added symbol tables. Closes #1813 

Minor change to wrong wingdings entry. There was something mixed up

2024-11-27 15:44 UTC, Mike-3 commented
change all to 1 bit color deep.

2024-11-27 16:10 UTC, Mike-3 requested changes

2024-11-27 16:10 UTC, Mike-3 commented on lib/tools/symbol_tables/_common/assets/honorius_thebanus/honorius_thebanus.zip
&.png -> ampersand.png

2024-11-27 16:10 UTC, Mike-3 commented on lib/tools/symbol_tables/_common/assets/iamiel_iadis_roy_des_artiques/iamiel_iadis_roy_des_artiques.zip
&.png -> ampersand.png

2024-11-27 16:10 UTC, Mike-3 commented on lib/tools/symbol_tables/_common/assets/livre_cinqiesme/livre_cinqiesme.zip
&.png -> ampersand.png

2024-11-27 16:10 UTC, Mike-3 commented on lib/tools/symbol_tables/_common/assets/nortman/nortman.zip
&.png -> ampersand.png
clean T

2024-11-27 16:10 UTC, Mike-3 commented on lib/tools/symbol_tables/_common/assets/ottride/ottride.zip
&.png -> ampersand.png

2024-11-27 16:10 UTC, Mike-3 commented on lib/tools/symbol_tables/_common/assets/tetragrammatique_v1/tetragrammatique_v1.zip
&.png -> ampersand.png

2024-11-27 16:10 UTC, Mike-3 commented on lib/tools/symbol_tables/_common/assets/tetragrammatique_v2/tetragrammatique_v2.zip
&.png -> ampersand.png

2024-11-27 16:10 UTC, Mike-3 commented on lib/application/i18n/assets/en.json
> +  "symboltables_allemans_germains_description": "Ancient secret writing from Trithemius (1561)",  "symboltables_alphabetum_arabum_title": "Alphabetum Arabum",
missing line break

2024-11-27 17:21 UTC, olliklee commented on lib/tools/symbol_tables/_common/assets/cicero/cicero.zip
Klein und Grossbuchstaben

2024-11-27 18:22 UTC, olliklee commented
Das sind alles Schwarzweiss Bilder. Jedes Programm macht da immer wieder ein 256 bit image draus, sobald es mit Transparenz handeln muss :(

2024-11-28 08:39 UTC, olliklee commented
All changes are made and your squeezed files are in.

2024-11-28 10:22 UTC, Mike-3 commented
Macht es nicht Sinn lieber  nur einen Text z.B. symbol_johannestrithemius anzulegen und den überall zuzuweisen, anstatt 16 mal das gleiche einzutragen ? Der gleiche Text muss ansonsten ja auch 16 mal übersetzt werden.
Also bei common und en.
Es gibt auch schon ein trithemius Eintrag, Vielleicht kann man den neuen Eintrag auch dort zuweisen.

2024-11-28 23:04 UTC, olliklee commented
Ja klar, Mark hat mir gezeigt, wie das bei den Lizenzen geht. Wusste nicht, dass das auch bei der Beschreibung geht und wie. Es sind 2 verschiedene Texte. Einmal für die 13 Schriften und dann für die 3 Freimaurer-Artigen. Gibt es bereits ein Beispiel?

2024-11-29 05:32 UTC, Mike-3 commented
z.B. 'binary'

2024-11-29 15:18 UTC, olliklee commented
I hope this is what you meant.

2024-11-29 15:20 UTC, olliklee commented
> Macht es nicht Sinn lieber nur einen Text z.B. symbol_johannestrithemius anzulegen und den überall zuzuweisen, anstatt 16 mal das gleiche einzutragen ? Der gleiche Text muss ansonsten ja auch 16 mal übersetzt werden. Also bei common und en. Es gibt auch schon ein trithemius Eintrag, Vielleicht kann man den neuen Eintrag auch dort zuweisen.

Ich würde den Eintrag so lassen. Der ist ja auch schon übersetzt und im Kontext auch etwas anders gehandhabt

2024-11-29 16:52 UTC, merged